import "./globals.css"; // Check the relative path
import Provider from "./provider"; // Ensure it's exported correctly
import ConvexClientProvider from "./ConvexClientProvider"; // Check for correct file name and export
import { Toaster } from "sonner";
import { icons } from "lucide-react";

export const metadata = {
  title: "Buildit",
  description: "Generated by create Buildit app",
  icons:{
    icon:['/favicon.ico?v=6'],
    apple:['/apple-touch-icon.png?.v=6'],
    shortcut:['/apple-touch-icon.png']
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-sky-900/60 via-transparent to-transparent">
        <ConvexClientProvider>
          <Provider>
            {children}
            <Toaster />
          </Provider>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
